version: '3'
services:
  a-backend-service-mock:
    image: a-backend-service:dev
    environment:
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=admin
      - MONGO_HOST=mongodb:27017
      - JWK_STORE=http://auth-mock:8084/jwk
    ports:
      - 8021:8080
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
  auth-mock:
    image: docker.pkg.github.com/informasjonsforvaltning/auth-utils-java/auth-utils-java:latest
    ports:
      - 8084:8084

