export const FETCH_REQUESTED = 'FETCH_SERVICE_ENDPOINTS_REQUESTED' as const;
export const FETCH_SUCCEEDED = 'FETCH_SERVICE_ENDPOINTS_SUCCEEDED' as const;
export const FETCH_FAILED = 'FETCH_SERVICE_ENDPOINTS_FAILED' as const;
export const FETCH_DETAILS_REQUESTED = 'FETCH_SERVICE_DETAILS_REQUESTED' as const;
export const FETCH_DETAILS_SUCCEEDED = 'FETCH_SERVICE_DETAILS_SUCCEEDED' as const;
export const FETCH_DETAILS_FAILED = 'FETCH_SERVICE_DETAILS_FAILED' as const;
